### ISSUE TITLE
Update response of Create Project

### ISSUE THREAD

**Issue by Gguidini** [apc-unb/apc-api#34]
The end-point to create projects returns the information listed below, note that the `id` of that new project submission is not returned.

<img width="899" alt="Screen Shot 2019-10-22 at 3 06 16 PM" src="https://user-images.githubusercontent.com/21023430/67316070-31630200-f4de-11e9-808b-ddb5d5765c25.png">

However it is necessary to update the Project status (as per documentation):

<img width="906" alt="Screen Shot 2019-10-22 at 3 06 28 PM" src="https://user-images.githubusercontent.com/21023430/67316041-227c4f80-f4de-11e9-80eb-ef15cdb0595b.png">

It would be beneficial to return the ID of the project along with the name and email of the monitor that was assigned to it, so that updates to the project's status can be done without having to get the entire list of project submissions for the student and look in it for the correct id.

Plus, with that arrangement the email sent to the designated monitor can include a link ready to update the project status upon being pressed.

This suggestion is open to debate, obviously, but I do think it's a good idea.

**Comment by VerasThiago** [comment]
> The end-point to create projects returns the information listed below, note that the `id` of that new project submission is not returned.
> 
> <img alt="Screen Shot 2019-10-22 at 3 06 16 PM" width="899" src="https://user-images.githubusercontent.com/21023430/67316070-31630200-f4de-11e9-808b-ddb5d5765c25.png">
> 
> However it is necessary to update the Project status (as per documentation):
> 
> <img alt="Screen Shot 2019-10-22 at 3 06 28 PM" width="906" src="https://user-images.githubusercontent.com/21023430/67316041-227c4f80-f4de-11e9-80eb-ef15cdb0595b.png">
> 
> It would be beneficial to return the ID of the project along with the name and email of the monitor that was assigned to it, so that updates to the project's status can be done without having to get the entire list of project submissions for the student and look in it for the correct id.
> 
> Plus, with that arrangement the email sent to the designated monitor can include a link ready to update the project status upon being pressed.
> 
> This suggestion is open to debate, obviously, but I do think it's a good idea.

This sugestion is very interesting because the monitor can easily update the project status, so that the student can know that the monitor have successfully received the e-mail.
