### ISSUE TITLE
Create route GET http://api.com/class/{professorid}

### ISSUE THREAD

**Issue by vitordullens** [apc-unb/apc-api#50]
To help the develop of the administrator's page, this endpoint "class/{professorid}" would be useful to get all the classes that have the same professor ministraiting it.

**Comment by VerasThiago** [comment]
This endpoint already exist. I only need to update the documentation

**Comment by VerasThiago** [comment]
Fixed in this [commit](https://github.com/apc-unb/apc-api/commit/67075a56e1a6e8418b21345df41615685a85deb1)

**Comment by VerasThiago** [comment]
Fixed in this [commit](https://github.com/apc-unb/apc-api/commit/67075a56e1a6e8418b21345df41615685a85deb1)
